### ISSUE TITLE
cannot link to Bgee database

### ISSUE THREAD

**Issue by kanglizhu** [BgeeDB/bgee_pipeline#18]
Hi,
I have installed BgeeDB and tried to  retrieve available species in the Bgee database using "listBgeeSpecies()", but  i failed to open the url you provided. 
Actually,  I have successfully ran BgeeDB last year, but recently it doesn't  work. 
![error message](https://user-images.githubusercontent.com/54318276/82630256-c371eb00-9c24-11ea-801c-285d1093b9b6.png)

Best regards,
kangli zhu

**Comment by jwollbrett** [comment]
Hello Kangli Zhu,

I am not able to reproduce your error. I checked the URL used to download species information and it is correct.
Maybe there was an internet connection problem when you tried to use BgeeDB.
Could you please try again and translate the message in english?
Which release of BgeeDB are you using? Did you try to install the last one on Bioconductor 3.11?
Do not hesitate to send a new message if your problem is still present.

**Comment by kanglizhu** [comment]
Hi,
I have solved this problem by running R under linux system. But  i still cannot figure out why it cannot work well under windows system, maybe there is something wrong with the internet connection.
Thank you so much for your reply.
